[package]
name = "my-redis"
version = "0.1.0"
edition = "2021"

[dependencies]
atoi = "2.0.0"
bytes = "1.6.0"
clap = { version = "4.5.4", features = ["derive"] }
tokio = { version = "1.37.0", features = ["full"] }
